# Generated by Django 4.1.5 on 2023-01-18 11:26

from django.db import migrations


def add_roles(apps, schema_editor):
    Role = apps.get_model('userprofile', 'Role')
    Role.objects.bulk_create([
        Role(name='superadmin'),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_roles),
    ]
